### ISSUE TITLE
bind is not a member of std::

### ISSUE THREAD

**Issue by guilhermesena1** [smithlabcode/epievo#4]
when I compile with g++ 7.3.0 I get the following error:
```
scale_tree.cpp: In function ‘int main(int, const char**)’:
scale_tree.cpp:106:22: error: ‘bind’ is not a member of ‘std’
                 std::bind(std::divides<double>(), std::placeholders::_1,
                      ^~~~
scale_tree.cpp:106:22: note: suggested alternative: ‘find’
                 std::bind(std::divides<double>(), std::placeholders::_1,
                      ^~~~
                      find
scale_tree.cpp:106:56: error: ‘std::placeholders’ has not been declared
                 std::bind(std::divides<double>(), std::placeholders::_1,
                                                        ^~~~~~~~~~~~
scale_tree.cpp:110:22: error: ‘bind’ is not a member of ‘std’
                 std::bind(std::multiplies<double>(), std::placeholders::_1,
                      ^~~~
scale_tree.cpp:110:22: note: suggested alternative: ‘find’
                 std::bind(std::multiplies<double>(), std::placeholders::_1,
                      ^~~~
                      find
scale_tree.cpp:110:59: error: ‘std::placeholders’ has not been declared
                 std::bind(std::multiplies<double>(), std::placeholders::_1,
                                                           ^~~~~~~~~~~~
scale_tree.cpp:115:20: error: ‘bind’ is not a member of ‘std’
               std::bind(std::multiplies<double>(), std::placeholders::_1,
                    ^~~~
scale_tree.cpp:115:20: note: suggested alternative: ‘find’
               std::bind(std::multiplies<double>(), std::placeholders::_1,
                    ^~~~
                    find
scale_tree.cpp:115:57: error: ‘std::placeholders’ has not been declared
               std::bind(std::multiplies<double>(), std::placeholders::_1,
                                                         ^~~~~~~~~~~~
```
